export const countries = [
  { name: 'Afghanistan', cities: ['Kaboul', 'Hérat', 'Mazar-i-Sharif', 'Kandahar'] },
  { name: 'Afrique du Sud', cities: ['Pretoria', 'Le Cap', 'Johannesbourg', 'Durban'] },
  { name: 'Albanie', cities: ['Tirana', 'Durrës', 'Vlorë', 'Elbasan'] },
  { name: 'Algérie', cities: ['Alger', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Sétif', 'Sidi Bel Abbès', 'Biskra', 'Tiaret'] },
  { name: 'Allemagne', cities: ['Berlin', 'Hambourg', 'Munich', 'Cologne', 'Francfort'] },
  { name: 'Andorre', cities: ['Andorre-la-Vieille'] },
  { name: 'Angola', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela'] },
  { name: 'Arabie Saoudite', cities: ['Riyad', 'Djeddah', 'La Mecque', 'Médine'] },
  { name: 'Argentine', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'] },
  { name: 'Arménie', cities: ['Erevan', 'Gyumri', 'Vanadzor'] },
  { name: 'Australie', cities: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane', 'Perth'] },
  { name: 'Autriche', cities: ['Vienne', 'Graz', 'Linz', 'Salzbourg'] },
  { name: 'Azerbaïdjan', cities: ['Bakou', 'Ganja', 'Sumqayit'] },
  { name: 'Bahamas', cities: ['Nassau'] },
  { name: 'Bahreïn', cities: ['Manama'] },
  { name: 'Bangladesh', cities: ['Dacca', 'Chittagong', 'Khulna'] },
  { name: 'Barbade', cities: ['Bridgetown'] },
  { name: 'Belgique', cities: ['Bruxelles', 'Anvers', 'Gand', 'Charleroi', 'Liège'] },
  { name: 'Belize', cities: ['Belmopan', 'Belize City'] },
  { name: 'Bénin', cities: ['Cotonou', 'Porto-Novo', 'Parakou', 'Abomey-Calavi', 'Djougou', 'Bohicon', 'Kandi', 'Abomey', 'Natitingou', 'Lokossa'] },
  { name: 'Bhoutan', cities: ['Thimphou'] },
  { name: 'Biélorussie', cities: ['Minsk', 'Gomel', 'Moguilev'] },
  { name: 'Birmanie', cities: ['Naypyidaw', 'Rangoun', 'Mandalay'] },
  { name: 'Bolivie', cities: ['Sucre', 'La Paz', 'Santa Cruz', 'Cochabamba'] },
  { name: 'Bosnie-Herzégovine', cities: ['Sarajevo', 'Banja Luka', 'Tuzla'] },
  { name: 'Botswana', cities: ['Gaborone', 'Francistown'] },
  { name: 'Brésil', cities: ['Brasília', 'São Paulo', 'Rio de Janeiro', 'Salvador'] },
  { name: 'Brunei', cities: ['Bandar Seri Begawan'] },
  { name: 'Bulgarie', cities: ['Sofia', 'Plovdiv', 'Varna'] },
  { name: 'Burkina Faso', cities: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora', 'Dédougou', 'Kaya', 'Dori', 'Tenkodogo', 'Fada N\'Gourma'] },
  { name: 'Burundi', cities: ['Gitega', 'Bujumbura'] },
  { name: 'Cambodge', cities: ['Phnom Penh', 'Battambang', 'Siem Reap'] },
  { name: 'Cameroun', cities: ['Douala', 'Yaoundé', 'Garoua', 'Bamenda', 'Maroua', 'Bafoussam', 'Ngaoundéré', 'Nkongsamba', 'Bertoua', 'Kumbo'] },
  { name: 'Canada', cities: ['Ottawa', 'Toronto', 'Montréal', 'Vancouver', 'Calgary'] },
  { name: 'Cap-Vert', cities: ['Praia', 'Mindelo'] },
  { name: 'Chili', cities: ['Santiago', 'Valparaíso', 'Concepción'] },
  { name: 'Chine', cities: ['Pékin', 'Shanghai', 'Canton', 'Shenzhen'] },
  { name: 'Chypre', cities: ['Nicosie', 'Limassol'] },
  { name: 'Colombie', cities: ['Bogota', 'Medellín', 'Cali', 'Barranquilla'] },
  { name: 'Comores', cities: ['Moroni'] },
  { name: 'Congo-Brazzaville', cities: ['Brazzaville', 'Pointe-Noire'] },
  { name: 'Congo-Kinshasa', cities: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga'] },
  { name: 'Corée du Nord', cities: ['Pyongyang'] },
  { name: 'Corée du Sud', cities: ['Séoul', 'Busan', 'Incheon'] },
  { name: 'Costa Rica', cities: ['San José'] },
  { name: 'Côte d\'Ivoire', cities: ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'Korhogo', 'San-Pédro', 'Gagnoa', 'Man', 'Divo', 'Anyama'] },
  { name: 'Croatie', cities: ['Zagreb', 'Split', 'Rijeka'] },
  { name: 'Cuba', cities: ['La Havane', 'Santiago de Cuba'] },
  { name: 'Danemark', cities: ['Copenhague', 'Aarhus', 'Odense'] },
  { name: 'Djibouti', cities: ['Djibouti'] },
  { name: 'Dominique', cities: ['Roseau'] },
  { name: 'Égypte', cities: ['Le Caire', 'Alexandrie', 'Gizeh', 'Port-Saïd'] },
  { name: 'Émirats arabes unis', cities: ['Abou Dabi', 'Dubaï', 'Charjah'] },
  { name: 'Équateur', cities: ['Quito', 'Guayaquil', 'Cuenca'] },
  { name: 'Érythrée', cities: ['Asmara'] },
  { name: 'Espagne', cities: ['Madrid', 'Barcelone', 'Valence', 'Séville'] },
  { name: 'Estonie', cities: ['Tallinn', 'Tartu'] },
  { name: 'Eswatini', cities: ['Mbabane', 'Lobamba'] },
  { name: 'États-Unis', cities: ['Washington', 'New York', 'Los Angeles', 'Chicago', 'Houston'] },
  { name: 'Éthiopie', cities: ['Addis-Abeba', 'Dire Dawa', 'Adama'] },
  { name: 'Fidji', cities: ['Suva'] },
  { name: 'Finlande', cities: ['Helsinki', 'Espoo', 'Tampere'] },
  { name: 'France', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'] },
  { name: 'Gabon', cities: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda', 'Mouila', 'Lambaréné', 'Tchibanga', 'Koulamoutou', 'Makokou'] },
  { name: 'Gambie', cities: ['Banjul', 'Serekunda'] },
  { name: 'Géorgie', cities: ['Tbilissi', 'Batoumi', 'Koutaïssi'] },
  { name: 'Ghana', cities: ['Accra', 'Kumasi', 'Tamale'] },
  { name: 'Grèce', cities: ['Athènes', 'Thessalonique', 'Patras'] },
  { name: 'Grenade', cities: ['Saint-Georges'] },
  { name: 'Guatemala', cities: ['Guatemala'] },
  { name: 'Guinée', cities: ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia', 'Labé', 'Guéckédou', 'Mamou', 'Boké', 'Kissidougou', 'Faranah'] },
  { name: 'Guinée-Bissau', cities: ['Bissau'] },
  { name: 'Guinée équatoriale', cities: ['Malabo', 'Bata'] },
  { name: 'Guyana', cities: ['Georgetown'] },
  { name: 'Haïti', cities: ['Port-au-Prince', 'Carrefour'] },
  { name: 'Honduras', cities: ['Tegucigalpa', 'San Pedro Sula'] },
  { name: 'Hongrie', cities: ['Budapest', 'Debrecen', 'Szeged'] },
  { name: 'Inde', cities: ['New Delhi', 'Bombay', 'Calcutta', 'Bangalore'] },
  { name: 'Indonésie', cities: ['Jakarta', 'Surabaya', 'Bandung'] },
  { name: 'Irak', cities: ['Bagdad', 'Bassora', 'Mossoul'] },
  { name: 'Iran', cities: ['Téhéran', 'Machhad', 'Ispahan'] },
  { name: 'Irlande', cities: ['Dublin', 'Cork', 'Limerick'] },
  { name: 'Islande', cities: ['Reykjavik'] },
  { name: 'Israël', cities: ['Jérusalem', 'Tel Aviv-Jaffa', 'Haïfa'] },
  { name: 'Italie', cities: ['Rome', 'Milan', 'Naples', 'Turin'] },
  { name: 'Jamaïque', cities: ['Kingston'] },
  { name: 'Japon', cities: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya'] },
  { name: 'Jordanie', cities: ['Amman', 'Zarqa', 'Irbid'] },
  { name: 'Kazakhstan', cities: ['Noursoultan', 'Almaty', 'Chimkent'] },
  { name: 'Kenya', cities: ['Nairobi', 'Mombasa', 'Kisumu'] },
  { name: 'Kirghizistan', cities: ['Bichkek', 'Och'] },
  { name: 'Kiribati', cities: ['Tarawa-Sud'] },
  { name: 'Koweït', cities: ['Koweït'] },
  { name: 'Laos', cities: ['Vientiane'] },
  { name: 'Lesotho', cities: ['Maseru'] },
  { name: 'Lettonie', cities: ['Riga', 'Daugavpils'] },
  { name: 'Liban', cities: ['Beyrouth', 'Tripoli', 'Sidon'] },
  { name: 'Liberia', cities: ['Monrovia'] },
  { name: 'Libye', cities: ['Tripoli', 'Benghazi', 'Misrata'] },
  { name: 'Liechtenstein', cities: ['Vaduz'] },
  { name: 'Lituanie', cities: ['Vilnius', 'Kaunas'] },
  { name: 'Luxembourg', cities: ['Luxembourg'] },
  { name: 'Macédoine du Nord', cities: ['Skopje', 'Bitola'] },
  { name: 'Madagascar', cities: ['Antananarivo', 'Toamasina', 'Antsirabe'] },
  { name: 'Malaisie', cities: ['Kuala Lumpur', 'George Town', 'Ipoh'] },
  { name: 'Malawi', cities: ['Lilongwe', 'Blantyre'] },
  { name: 'Maldives', cities: ['Malé'] },
  { name: 'Mali', cities: ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Kayes', 'Ségou', 'Gao', 'Tombouctou', 'Ménaka', 'Kidal'] },
  { name: 'Malte', cities: ['La Valette'] },
  { name: 'Maroc', cities: ['Rabat', 'Casablanca', 'Fès', 'Tanger', 'Marrakech', 'Salé', 'Meknès', 'Oujda', 'Kenitra', 'Agadir'] },
  { name: 'Marshall', cities: ['Majuro'] },
  { name: 'Maurice', cities: ['Port-Louis'] },
  { name: 'Mauritanie', cities: ['Nouakchott', 'Nouadhibou'] },
  { name: 'Mexique', cities: ['Mexico', 'Guadalajara', 'Monterrey', 'Puebla'] },
  { name: 'Micronésie', cities: ['Palikir'] },
  { name: 'Moldavie', cities: ['Chisinau', 'Tiraspol'] },
  { name: 'Monaco', cities: ['Monaco'] },
  { name: 'Mongolie', cities: ['Oulan-Bator'] },
  { name: 'Monténégro', cities: ['Podgorica'] },
  { name: 'Mozambique', cities: ['Maputo', 'Matola', 'Beira'] },
  { name: 'Namibie', cities: ['Windhoek'] },
  { name: 'Nauru', cities: ['Yaren'] },
  { name: 'Népal', cities: ['Katmandou', 'Pokhara'] },
  { name: 'Nicaragua', cities: ['Managua'] },
  { name: 'Niger', cities: ['Niamey', 'Zinder', 'Maradi', 'Tahoua', 'Agadez', 'Arlit', 'Birni N\'Konni', 'Dosso', 'Gaya', 'Tessaoua'] },
  { name: 'Nigeria', cities: ['Abuja', 'Lagos', 'Kano', 'Ibadan'] },
  { name: 'Norvège', cities: ['Oslo', 'Bergen', 'Trondheim'] },
  { name: 'Nouvelle-Zélande', cities: ['Wellington', 'Auckland', 'Christchurch'] },
  { name: 'Oman', cities: ['Mascate'] },
  { name: 'Ouganda', cities: ['Kampala', 'Gulu', 'Lira'] },
  { name: 'Ouzbékistan', cities: ['Tachkent', 'Namangan', 'Samarcande'] },
  { name: 'Pakistan', cities: ['Islamabad', 'Karachi', 'Lahore', 'Faisalabad'] },
  { name: 'Palaos', cities: ['Melekeok'] },
  { name: 'Palestine', cities: ['Jérusalem-Est', 'Gaza', 'Hébron'] },
  { name: 'Panama', cities: ['Panama'] },
  { name: 'Papouasie-Nouvelle-Guinée', cities: ['Port Moresby'] },
  { name: 'Paraguay', cities: ['Asuncion'] },
  { name: 'Pays-Bas', cities: ['Amsterdam', 'Rotterdam', 'La Haye', 'Utrecht'] },
  { name: 'Pérou', cities: ['Lima', 'Arequipa', 'Trujillo'] },
  { name: 'Philippines', cities: ['Manille', 'Quezon City', 'Davao'] },
  { name: 'Pologne', cities: ['Varsovie', 'Cracovie', 'Łódź', 'Wrocław'] },
  { name: 'Portugal', cities: ['Lisbonne', 'Porto'] },
  { name: 'Qatar', cities: ['Doha'] },
  { name: 'République centrafricaine', cities: ['Bangui'] },
  { name: 'République dominicaine', cities: ['Saint-Domingue'] },
  { name: 'République tchèque', cities: ['Prague', 'Brno', 'Ostrava'] },
  { name: 'Roumanie', cities: ['Bucarest', 'Cluj-Napoca', 'Timișoara'] },
  { name: 'Royaume-Uni', cities: ['Londres', 'Birmingham', 'Glasgow', 'Liverpool'] },
  { name: 'Russie', cities: ['Moscou', 'Saint-Pétersbourg', 'Novossibirsk', 'Iekaterinbourg'] },
  { name: 'Rwanda', cities: ['Kigali', 'Butare', 'Gisenyi'] },
  { name: 'Saint-Christophe-et-Niévès', cities: ['Basseterre'] },
  { name: 'Sainte-Lucie', cities: ['Castries'] },
  { name: 'Saint-Marin', cities: ['Saint-Marin'] },
  { name: 'Saint-Vincent-et-les-Grenadines', cities: ['Kingstown'] },
  { name: 'Salomon', cities: ['Honiara'] },
  { name: 'Salvador', cities: ['San Salvador'] },
  { name: 'Samoa', cities: ['Apia'] },
  { name: 'Sao Tomé-et-Principe', cities: ['Sao Tomé'] },
  { name: 'Sénégal', cities: ['Dakar', 'Thiès', 'Saint-Louis', 'Mbour', 'Kaolack', 'Ziguinchor', 'Diourbel', 'Louga', 'Tambacounda', 'Kolda'] },
  { name: 'Serbie', cities: ['Belgrade', 'Novi Sad', 'Niš'] },
  { name: 'Seychelles', cities: ['Victoria'] },
  { name: 'Sierra Leone', cities: ['Freetown'] },
  { name: 'Singapour', cities: ['Singapour'] },
  { name: 'Slovaquie', cities: ['Bratislava', 'Košice'] },
  { name: 'Slovénie', cities: ['Ljubljana'] },
  { name: 'Somalie', cities: ['Mogadiscio'] },
  { name: 'Soudan', cities: ['Khartoum', 'Omdourman'] },
  { name: 'Soudan du Sud', cities: ['Djouba'] },
  { name: 'Sri Lanka', cities: ['Sri Jayawardenepura Kotte', 'Colombo'] },
  { name: 'Suède', cities: ['Stockholm', 'Göteborg', 'Malmö'] },
  { name: 'Suisse', cities: ['Berne', 'Zurich', 'Genève', 'Bâle'] },
  { name: 'Suriname', cities: ['Paramaribo'] },
  { name: 'Syrie', cities: ['Damas', 'Alep', 'Homs'] },
  { name: 'Tadjikistan', cities: ['Douchanbé'] },
  { name: 'Tanzanie', cities: ['Dodoma', 'Dar es Salam'] },
  { name: 'Tchad', cities: ['N\'Djaména', 'Moundou', 'Sarh'] },
  { name: 'Thaïlande', cities: ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima'] },
  { name: 'Timor oriental', cities: ['Dili'] },
  { name: 'Togo', cities: ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Kpalimé', 'Dapaong', 'Tsevié', 'Aného', 'Sansanné-Mango', 'Bafilo'] },
  { name: 'Tonga', cities: ['Nuku\'alofa'] },
  { name: 'Trinité-et-Tobago', cities: ['Port-d\'Espagne'] },
  { name: 'Tunisie', cities: ['Tunis', 'Sfax', 'Sousse'] },
  { name: 'Turkménistan', cities: ['Achgabat'] },
  { name: 'Turquie', cities: ['Ankara', 'Istanbul', 'Izmir', 'Bursa'] },
  { name: 'Tuvalu', cities: ['Vaiaku'] },
  { name: 'Ukraine', cities: ['Kiev', 'Kharkiv', 'Odessa', 'Dnipro'] },
  { name: 'Uruguay', cities: ['Montevideo'] },
  { name: 'Vanuatu', cities: ['Port-Vila'] },
  { name: 'Vatican', cities: ['Vatican'] },
  { name: 'Venezuela', cities: ['Caracas', 'Maracaibo', 'Valence'] },
  { name: 'Viêt Nam', cities: ['Hanoï', 'Hô Chi Minh-Ville', 'Da Nang'] },
  { name: 'Yémen', cities: ['Sanaa', 'Aden'] },
  { name: 'Zambie', cities: ['Lusaka', 'Ndola'] },
  { name: 'Zimbabwe', cities: ['Harare', 'Bulawayo'] }
];
