import { UserRole } from '../types';

export type Action = 
  | 'PRODUCT_CREATE' | 'PRODUCT_UPDATE' | 'PRODUCT_DELETE' | 'PRODUCT_READ'
  | 'TRANSACTION_CREATE' | 'TRANSACTION_UPDATE' | 'TRANSACTION_DELETE' | 'TRANSACTION_READ'
  | 'USER_CREATE' | 'USER_UPDATE' | 'USER_DELETE' | 'USER_READ'
  | 'TIERS_CREATE' | 'TIERS_UPDATE' | 'TIERS_DELETE' | 'TIERS_READ'
  | 'FINANCE_READ' | 'FINANCE_EXPORT' | 'FINANCE_CREATE' | 'FINANCE_DELETE'
  | 'COMPANY_UPDATE'
  | 'ADMIN_ACCESS' | 'SYSTEM_RESET';

const ROLE_PERMISSIONS: Record<UserRole, Action[]> = {
  'ADMIN': [
    'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_DELETE', 'PRODUCT_READ',
    'TRANSACTION_CREATE', 'TRANSACTION_UPDATE', 'TRANSACTION_DELETE', 'TRANSACTION_READ',
    'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_READ',
    'TIERS_CREATE', 'TIERS_UPDATE', 'TIERS_DELETE', 'TIERS_READ',
    'FINANCE_READ', 'FINANCE_EXPORT', 'FINANCE_CREATE', 'FINANCE_DELETE',
    'COMPANY_UPDATE',
    'ADMIN_ACCESS', 'SYSTEM_RESET'
  ],
  'ADMINISTRATEUR_ERP': [
    'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_DELETE', 'PRODUCT_READ',
    'TRANSACTION_CREATE', 'TRANSACTION_UPDATE', 'TRANSACTION_DELETE', 'TRANSACTION_READ',
    'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_READ',
    'TIERS_CREATE', 'TIERS_UPDATE', 'TIERS_DELETE', 'TIERS_READ',
    'FINANCE_READ', 'FINANCE_EXPORT', 'FINANCE_CREATE', 'FINANCE_DELETE',
    'COMPANY_UPDATE',
    'ADMIN_ACCESS', 'SYSTEM_RESET'
  ],
  'GESTIONNAIRE_ERP': [
    'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_READ',
    'TRANSACTION_CREATE', 'TRANSACTION_UPDATE', 'TRANSACTION_READ',
    'USER_CREATE', 'USER_UPDATE', 'USER_READ',
    'TIERS_CREATE', 'TIERS_UPDATE', 'TIERS_READ',
    'FINANCE_READ', 'FINANCE_EXPORT',
    'COMPANY_UPDATE',
    'ADMIN_ACCESS'
  ],
  'ADMINISTRATEUR_KONTROL': [
    'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_DELETE', 'PRODUCT_READ',
    'TRANSACTION_CREATE', 'TRANSACTION_UPDATE', 'TRANSACTION_DELETE', 'TRANSACTION_READ',
    'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_READ',
    'TIERS_CREATE', 'TIERS_UPDATE', 'TIERS_DELETE', 'TIERS_READ',
    'FINANCE_READ', 'FINANCE_EXPORT', 'FINANCE_CREATE', 'FINANCE_DELETE',
    'COMPANY_UPDATE',
    'ADMIN_ACCESS'
  ],
  'GESTIONNAIRE_KONTROL': [
    'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_READ',
    'TRANSACTION_CREATE', 'TRANSACTION_UPDATE', 'TRANSACTION_READ',
    'USER_CREATE', 'USER_UPDATE', 'USER_READ',
    'TIERS_CREATE', 'TIERS_UPDATE', 'TIERS_READ',
    'FINANCE_READ', 'FINANCE_EXPORT',
    'COMPANY_UPDATE',
    'ADMIN_ACCESS'
  ],
  'ADMINISTRATEUR_ENTREPRISE': [
    'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_DELETE', 'PRODUCT_READ',
    'TRANSACTION_CREATE', 'TRANSACTION_UPDATE', 'TRANSACTION_DELETE', 'TRANSACTION_READ',
    'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_READ',
    'TIERS_CREATE', 'TIERS_UPDATE', 'TIERS_DELETE', 'TIERS_READ',
    'FINANCE_READ', 'FINANCE_EXPORT', 'FINANCE_CREATE', 'FINANCE_DELETE',
    'COMPANY_UPDATE'
  ],
  'GESTIONNAIRE_ENTREPRISE': [
    'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_READ',
    'TRANSACTION_CREATE', 'TRANSACTION_READ',
    'USER_READ',
    'TIERS_CREATE', 'TIERS_READ',
    'FINANCE_READ'
  ],
  'UTILISATEUR': [
    'PRODUCT_READ',
    'TRANSACTION_READ',
    'TIERS_READ',
    'FINANCE_READ'
  ]
};

export function hasPermission(role: UserRole | undefined, action: Action): boolean {
  if (!role) return false;
  return ROLE_PERMISSIONS[role]?.includes(action) || false;
}
